@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

!global $USC_DESC = "Platform wide tool and functional implementations including authentication and authorization, metrics publication, logging services, deployment and build systems"
!global $AS_DESC = "Higher level data functions to access and transform data."
!global $ADS_DESC = "Subsystem for developing and assembling science algorithms into an algorithm catalog"
!global $SPS_DESC = "Subsystem for the generation of science data products through the combination of Algorithms and Data"
!global $DS_DESC = "Subsystem for ingestion, storage, and access to data products for use in the Unity System."


LAYOUT_WITH_LEGEND()

Person(ad, "Algorithm Developer", "Teams responsible for the development of science algorithms")
Person(op, "Operator", "Teams responsible for the operational production and monitoring of products.")
Person(cv, "Cal/Val", "Teams responsible for the calibration & validation of data products.")
Person_Ext(ou, "Other User", "Users interested in examining data products, algorithm prototypes, or 'open science' style investigations of product generation  (reproduce, re-run, examine).")

System_Ext(di, "Data Inputs", "Originating point of data for the project/science teams to process into higher level products.")
System_Ext(a, "Archive", "Long term archive for distribution of data products to end users. Examples include PDS, DAAC, or other NASA approved entity.")

System_Boundary(u, "Unity") {
    Container(ads, "Algorithm Development", $ADS_DESC)
    Container(sps, "Science Processing", $SPS_DESC)
    Container_Boundary(dapa, "Data Access and Processing API") {
      Container(ds, "Data Services", $DS_DESC)
      Container(as, "Analysis Services", $AS_DESC)
    }
    Container(cs, "Common Services", $USC_DESC)

    Rel(ads, sps, "Algorithm Catalog", "API")
}

Rel(di, ds, "Deliver or stage data products for processing")
Rel(ds, a, "Sends data to archive")
Rel(ad, ads, "Login to develop algorithms, test algorithms, operationalize workflows, execute and monitor operational workflows, validate products", "UI")
Rel(op, sps, "ensure ongoing product generation, monitor processing, triage issues, ensure archive delivery")
Rel(cv,ads, "Calibrate algorithms and validate generated data using existing data products")
Rel(ou, dapa, "Users interested in examining data products, algorithm prototypes, or 'open science' style investigations of product generation  (reproduce, re-run, examine)")
Rel(dapa, sps, "Provides data to processing system and catalogs processing results")

@enduml
