@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist

!includeurl AWSPuml/AWSCommon.puml
' !includeurl AWSPuml/BusinessApplications/all.puml
!include AWSPuml/Storage/SimpleStorageServiceBucketWithObjects.puml

LAYOUT_WITH_LEGEND()

System_Ext(sps, "Science Processing System", "")
System_Boundary(ads,"Algorithm Development"){
  Container(bs, "Build System", "Jenkins", "Builds algorithms into OGC Algorithm Packages.")
  Container_Boundary(ac, "Application Catalog") {
      Component(api, "Application Package Catalog", "dockstore", "API for listing, viewing, and posting package metadata")
      Component(store, "Application Store", "ecr/github", "where docker images are stored", $sprite="SimpleStorageServiceBucketWithObjects")
      Component(db, "database", "postgres", "Where metadata is stored for packages" )

      Rel(api, db, "reads/writes package metadata", "JSON/HTTPS")

}

}
Rel(sps, api, "Gets Package Info", "JSON/HTTPS")

Rel(bs, store, "Writes OGC Package container");
Rel(bs, api, "Registers OGC Package CWL/Metadata");

@enduml
