@startuml
title Algorithm Execution

start
note right
  **data stagein Volume** and input.json
  ====
  files staged
  top level STAC catalog.json
end note

partition "Input Processor" {
  :read STAC Catalog;
  :map inputs to command line or configuration based file;
  :create algorithm execution 'command' with input parameters;
}

:Algorithm execution;

partition "Output Processor" {
    :Generate stac items/document for each file in output path;
    :Generate stac catalog.json;
}

stop
note right
  Data StageOut Volume
  + Catalog.json (STAC Catalog)
  ====
  File organized in out folder with STAC Documents
end note



@enduml
